/*
   This file was generated automatically by Alchitry Labs version 1.1.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

/*
   Parameters:
     TOP = 49999999
*/
module timer_4 (
    input clk,
    input rst,
    output reg out
  );
  
  localparam TOP = 26'h2faf07f;
  
  
  reg [25:0] M_counter_d, M_counter_q = 1'h0;
  reg [0:0] M_pulse_d, M_pulse_q = 1'h0;
  
  always @* begin
    M_pulse_d = M_pulse_q;
    M_counter_d = M_counter_q;
    
    M_pulse_d = 1'h0;
    out = M_pulse_q;
    M_counter_d = M_counter_q + 1'h1;
    if (M_counter_q == 26'h2faf07f) begin
      M_counter_d = 1'h0;
      M_pulse_d = 1'h1;
    end
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_counter_q <= 1'h0;
      M_pulse_q <= 1'h0;
    end else begin
      M_counter_q <= M_counter_d;
      M_pulse_q <= M_pulse_d;
    end
  end
  
endmodule
